services:
  api:
    build:
      context: ..
      dockerfile: reup-notify-node/Dockerfile
    image: reup-notify-node:local
    container_name: reup-notify-node-api
    command: ["api"]
    restart: unless-stopped
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - REDIS_URL=redis://reup-redis:6379/0
    ports:
      - "8109:8000"
    volumes:
      - ./data/source:/source
      - ./data/config:/config
    networks:
      - reup-net

  worker:
    build:
      context: ..
      dockerfile: reup-notify-node/Dockerfile
    image: reup-notify-node:local
    container_name: reup-notify-node-worker
    command: ["worker"]
    restart: unless-stopped
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - REDIS_URL=redis://reup-redis:6379/0
      - EVENT_LOG_ENABLED=true
    volumes:
      - ./data/source:/source
      - ./data/config:/config
      - ./data/logs:/logs
    networks:
      - reup-net

networks:
  reup-net:
    external: true
